### PR TITLE
Change to 250 characters max as said in the fb doc

### PR DESCRIPTION
**Pull request by GautierT**
Hi,
The doc say it's max 250 characters. Not 50.
https://developers.facebook.com/docs/messenger-platform/plugin-reference/send-to-messenger

### CODE REVIEW

**Comment by lemieux** [comment]
The Messenger platform is still in beta and that limit most likely increased since this component was written. 

Thanks for the contribution! I'll release the update right away.

**Comment by lemieux** [comment]
Version 1.0.2 is out with your changes.

Thanks again!

**Comment by GautierT** [comment]
Thanks for updating so fast !

**Comment by lemieux** [comment]
No problem, issues that come with their fix are usually the easiest :smile:

**Pull request merged**
